# Cloud Build Configuration for Singapore Haze Prediction System
# Triggers on push to main branch

steps:
  # Step 0: Fetch Git LFS files
  - name: 'gcr.io/cloud-builders/git'
    id: 'fetch-lfs-files'
    args:
      - 'lfs'
      - 'pull'
    timeout: 300s

  # Step 1: Build Docker image for API
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-api-image'
    args:
      - 'build'
      - '--platform=linux/amd64'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/haze-prediction/haze-api:${SHORT_SHA}'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/haze-prediction/haze-api:latest'
      - '.'
    timeout: 600s

  # Step 2: Build Docker image for Scheduler
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-scheduler-image'
    args:
      - 'build'
      - '--platform=linux/amd64'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/haze-prediction/haze-scheduler:${SHORT_SHA}'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/haze-prediction/haze-scheduler:latest'
      - '.'
    timeout: 600s

  # Step 3: Get API URL for build-time injection (deploy API first to get URL)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'get-api-url'
    entrypoint: bash
    args:
      - '-c'
      - |
        # Check if API service exists
        if gcloud run services describe haze-prediction-api --region=asia-southeast1 &>/dev/null; then
          API_URL=$(gcloud run services describe haze-prediction-api \
            --region=asia-southeast1 \
            --format="value(status.url)")
          echo "Using existing API URL: $${API_URL}"
        else
          API_URL="https://haze-prediction-api-placeholder.run.app"
          echo "API service not yet deployed, using placeholder: $${API_URL}"
        fi
        echo "$${API_URL}" > /workspace/api_url.txt
    waitFor: ['-']

  # Step 4: Build Docker image for UI with API URL
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-ui-image'
    entrypoint: bash
    args:
      - '-c'
      - |
        API_URL=$(cat /workspace/api_url.txt)
        docker build \
          --platform=linux/amd64 \
          --build-arg NEXT_PUBLIC_API_URL=$${API_URL} \
          -t asia-southeast1-docker.pkg.dev/${PROJECT_ID}/haze-prediction/haze-ui:${SHORT_SHA} \
          -t asia-southeast1-docker.pkg.dev/${PROJECT_ID}/haze-prediction/haze-ui:latest \
          -f ui-nextjs/Dockerfile \
          ./ui-nextjs
    timeout: 600s
    waitFor: ['get-api-url']

  # Step 5: Push API image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-api-image'
    args:
      - 'push'
      - '--all-tags'
      - 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/haze-prediction/haze-api'
    waitFor: ['build-api-image']

  # Step 6: Push Scheduler image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-scheduler-image'
    args:
      - 'push'
      - '--all-tags'
      - 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/haze-prediction/haze-scheduler'
    waitFor: ['build-scheduler-image']

  # Step 7: Push UI image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-ui-image'
    args:
      - 'push'
      - '--all-tags'
      - 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/haze-prediction/haze-ui'
    waitFor: ['build-ui-image']

  # Step 8: Deploy API to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-api'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'haze-prediction-api'
      - '--image'
      - 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/haze-prediction/haze-api:${SHORT_SHA}'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8000'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'ENVIRONMENT=production'
      - '--set-secrets'
      - 'FIRMS_MAP_KEY=firms-api-key:latest,DATABASE_URL=database-url:latest'
      - '--add-cloudsql-instances'
      - 'hacx-477608:asia-southeast1:haze-prediction-db'
    waitFor: ['push-api-image']

  # Step 9: Deploy UI to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-ui'
    entrypoint: bash
    args:
      - '-c'
      - |
        gcloud run deploy haze-prediction-ui \
          --image=asia-southeast1-docker.pkg.dev/${PROJECT_ID}/haze-prediction/haze-ui:${SHORT_SHA} \
          --region=asia-southeast1 \
          --platform=managed \
          --allow-unauthenticated \
          --port=3000 \
          --memory=256Mi \
          --cpu=1 \
          --min-instances=0 \
          --max-instances=5 \
          --timeout=60 \
          --set-env-vars="NODE_ENV=production"
    waitFor: ['deploy-api', 'push-ui-image']

  # Note: Models are now included directly in Docker images
  # No need to upload to GCS separately - they're always in sync with code!

  # Step 6: Run tests (optional - uncomment if you have tests)
  # - name: 'python:3.13-slim'
  #   id: 'run-tests'
  #   entrypoint: bash
  #   args:
  #     - '-c'
  #     - |
  #       pip install -r requirements.txt
  #       pytest tests/ -v
  #   waitFor: ['-']

# Images to be pushed to Artifact Registry
images:
  - 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/haze-prediction/haze-api:${SHORT_SHA}'
  - 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/haze-prediction/haze-api:latest'
  - 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/haze-prediction/haze-scheduler:${SHORT_SHA}'
  - 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/haze-prediction/haze-scheduler:latest'
  - 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/haze-prediction/haze-ui:${SHORT_SHA}'
  - 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/haze-prediction/haze-ui:latest'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  substitutionOption: 'ALLOW_LOOSE'

# Timeout for entire build
timeout: 1200s

# Substitutions (variables)
substitutions:
  _REGION: 'asia-southeast1'
  _SERVICE_NAME: 'haze-prediction-api'
